### ISSUE TITLE
GIFs of features are not shown on Safari (Desktop)

### ISSUE THREAD

**Issue by wtphilip** [stormkit-io/www-stormkit-io#53] opened 2020-06-08 13:24 UTC
When accessing the landing page with Safari on Desktop, it only shows a pulsating dot in the middle of the GIF that normally show the features.. 

1. Open Safari
2. Enter stormkit.io
3. Scroll down to the GIF and select a different feature in the selection to the left
(same happens with every GIF, even when selecting it)

I would expect the visuals to appear that I see with Chrome or Brave. 

Desktop:
 - OS: iOS
 - Browser: safari
 - Version: 13.0.5

![0eab9997-11e4-4349-999c-4cea623dd629](https://user-images.githubusercontent.com/38620360/84035502-24771e00-a99c-11ea-9951-fd971b5d435c.jpg)

**Comment by svedova** [comment] 2020-07-16 10:30
Thanks @wtphilip for submitting this. 

I've dug into this bug a bit deeper and found out that the real problem is not caused by the client side, but rather by the server side. 

Safari uses `Byte Ranges` for streaming videos and Stormkit server didn't support it so far. So I went ahead and added support for these headers and now it works as expected :) 

I'm going to close this issue please feel free to re-open if you see any similar behaviour.

**Closed by svedova** 2020-07-16 10:30 UTC
